# Generated by Django 5.2.17 on 2026-10-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='editorials/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_mobile',
            field=models.ImageField(blank=True, upload_to='editorials/'),
        ),
    ]
